changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: Breaking Changes
      labels:
        - BREAKING CHANGE
        - major
    - title: New Features 🎉
      labels:
        - minor
        - feat
    - title: A bug fixes
      labels:
        - fix
        - patch
    - title: Other Changes
      labels:
        - '*'
