name: (NEW) Test Installation of sitecore-cloudsdk release candidate across various frameworks

on:
  workflow_run:
    workflows: ['Pull Request']
    types:
      - completed
  workflow_dispatch:

jobs:
  na:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
