name: (OLD) Test Installation of sitecore-cloudsdk release candidate across various frameworks

on:
  workflow_run:
    workflows: ['Pull Request']
    types:
      - completed
  workflow_dispatch:

jobs:
  next-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci
      - name: Create npm link for personalize
        run: |
          npx nx run personalize:build && npx nx run events:build
          cd ./packages/events/          
          npm link
          cd ../personalize/
          npm link
      - name: Create Next app
        run: |
          cd ../          
          npx create-next-app@14.1 my-next-app-old --ts --no-eslint --no-tailwind --no-src-dir --no-app --import-alias '@/*'
      - name: Install Cypress, dependencies and supporting files
        run: |
          cd ../my-next-app-old
          npm install cypress
          cp -r $GITHUB_WORKSPACE/tools/testing_resources/installation-test/cypress-template/*  ./          
          mv ./cypress/e2e/sanity-test-template-old.txt ./cypress/e2e/test.cy.js
          mv ./cypress-config.txt ./cypress.config.js
          npm install --save-dev start-server-and-test
          npm pkg set 'scripts.test'='npx cypress run' 'scripts.start-server'='npx next dev' 'scripts.ci'='npx start-server-and-test start-server 3000 test'
          cat package.json
      - name: Install @sitecore libraries using npm link
        run: |
          cd ../my-next-app-old
          npm link @sitecore-cloudsdk/events --save
          npm link @sitecore-cloudsdk/personalize --save
          cp $GITHUB_WORKSPACE/tools/testing_resources/installation-test/app-templates/next-app-old/page-template.txt ./pages/index.tsx
          cp $GITHUB_WORKSPACE/tools/testing_resources/installation-test/app-templates/next-app-old/middleware-template.txt ./middleware.ts
      - name: Build Next app
        run: |
          cd ../my-next-app-old
          npm run build
      - name: Run Next App & Cypress Sanity Test
        run: |
          cd ../my-next-app-old
          npx next --version
          npm run ci
