name: Run Veracode pipeline scan
on:
  workflow_dispatch:
    inputs:
      strictMode:
        description: 'Perform a Strict run?'
        default: false
        type: boolean
  push:
    branches:
      - 'master'

jobs:
  veracode-scan:
    name: Run Veracode Scan
    uses: Sitecore-Internal/sitecore.devops.github.workflow.veracodescan.raw/.github/workflows/VeracodeScanRaw.yaml@V1
    secrets: inherit
    with:
      ProjectName: cloudSDK
      DirectoryToScan: packages
      SeverityRequirement: ${{inputs.strictMode == true && '"Informational, Very Low, Low, Medium, High, Very High"' || '"High, Very High"'}}
