name: Run Veracode pipeline scan
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  veracode-scan:
    name: Run Veracode
    uses: Sitecore-Internal/sitecore.devops.github.workflow.veracodescan.raw/.github/workflows/VeracodeScanRaw.yaml@V1
    secrets: inherit
    with:
      ProjectName: cloudSDK
      DirectoryToScan: packages
      SeverityRequirement: '"High, Very High"'
